name: Pull RSS on schedule

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '0 10 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: node ./dist/src/pull-rss.js
