name: CI

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: My custom action
      uses: gordey4doronin/add-new-version@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
